project:
  type: website
  output-dir: docs
website:
  title: "Uraz's R and Python Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/urazakgul
      - icon: twitter
        href: https://twitter.com/handsonrpy
format:
  html:
    theme: darkly
    css: styles.css



